# Étape 1 : Build de l'application
FROM openjdk:21-jdk as builder

WORKDIR /app

# Copier les fichiers de configuration Maven
COPY pom.xml ./
COPY .mvn/ .mvn/
COPY mvnw ./

# Télécharger les dépendances
RUN ./mvnw dependency:go-offline

# Copier le code source et construire l'application
COPY src ./src
RUN ./mvnw clean package -DskipTests

# Étape 2 : Image de production
FROM openjdk:21-jre-slim

WORKDIR /app

# Copier le JAR depuis l'étape de build
COPY --from=builder /app/target/*.jar app.jar

# Exposer le port
EXPOSE 5050

# Commande pour démarrer l'application
CMD ["java", "-jar", "app.jar"]
